spring.application.name=demo
spring.datasource.url=jdbc:postgresql://ep-hidden-dust-atdsv1uv-pooler.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require

spring.datasource.username=neondb_owner

spring.datasource.password=npg_x90damnjGJuE

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.security.user.name=admin
spring.security.user.password=admin
